apiVersion: apps/v1
kind: Deployment
metadata:
  name: prumex-deployment
  labels:
    app: prumex
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prumex
  template:
    metadata:
      labels:
        app: prumex
    spec:
      containers:
      - name: prumex
        # REPLACE WITH YOUR IMAGE NAME (e.g., dambor/prumex:latest)
        image: prumex:latest 
        imagePullPolicy: IfNotPresent # Useful for local testing if image isn't pushed
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: prumex-service
spec:
  selector:
    app: prumex
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Change to ClusterIP or NodePort based on your environment
